"""Migration

Revision ID: 49217bb5099d
Revises: 35a1517ee139
Create Date: 2019-11-26 04:51:05.014384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49217bb5099d'
down_revision = '35a1517ee139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
